/**
 * Test Helpers
 * Common utilities for testing
 */

const jwt = require('jsonwebtoken');
const mongoose = require('mongoose');

/**
 * Create a mock user for testing
 */
const createMockUser = (overrides = {}) => ({
  _id: new mongoose.Types.ObjectId(),
  name: 'Test User',
  email: 'test@example.com',
  activeCareerId: null,
  isEarlyAccess: false,
  createdAt: new Date(),
  ...overrides
});

/**
 * Generate a valid JWT token for testing
 */
const generateTestToken = (userId) => {
  return jwt.sign(
    { id: userId.toString() },
    process.env.JWT_SECRET || 'test-secret-key',
    { expiresIn: '1d' }
  );
};

/**
 * Create mock request object
 */
const mockRequest = (overrides = {}) => ({
  user: createMockUser(),
  params: {},
  query: {},
  body: {},
  headers: {},
  ...overrides
});

/**
 * Create mock response object
 */
const mockResponse = () => {
  const res = {};
  res.status = jest.fn().mockReturnValue(res);
  res.json = jest.fn().mockReturnValue(res);
  res.send = jest.fn().mockReturnValue(res);
  res.setHeader = jest.fn().mockReturnValue(res);
  return res;
};

/**
 * Create mock next function
 */
const mockNext = () => jest.fn();

/**
 * Create a test learning path
 */
const createTestLearningPath = (userId, overrides = {}) => ({
  _id: new mongoose.Types.ObjectId(),
  userId,
  title: 'Test Learning Path',
  description: 'A test path for unit testing',
  careerId: 'frontend-developer',
  isAutoGenerated: false,
  status: 'active',
  visibility: 'private',
  structureGraph: {
    nodes: [
      {
        id: 'node_1',
        videoId: 'test-video-1',
        title: 'Test Video 1',
        thumbnailUrl: 'https://example.com/thumb1.jpg',
        duration: 600,
        channelTitle: 'Test Channel',
        order: 0,
        isCompleted: false
      },
      {
        id: 'node_2',
        videoId: 'test-video-2',
        title: 'Test Video 2',
        thumbnailUrl: 'https://example.com/thumb2.jpg',
        duration: 900,
        channelTitle: 'Test Channel',
        order: 1,
        isCompleted: false
      }
    ],
    edges: [
      { from: 'node_1', to: 'node_2', type: 'prerequisite' }
    ]
  },
  inferredSkills: ['javascript', 'react'],
  inferredCareers: ['frontend-developer'],
  totalNodesCount: 2,
  completedNodesCount: 0,
  createdAt: new Date(),
  ...overrides
});

/**
 * Create a test saved video
 */
const createTestSavedVideo = (userId, overrides = {}) => ({
  _id: new mongoose.Types.ObjectId(),
  userId,
  videoId: `video-${Date.now()}`,
  title: 'Test Video',
  description: 'A test video for testing',
  thumbnailUrl: 'https://example.com/thumb.jpg',
  channelTitle: 'Test Channel',
  channelId: 'test-channel-id',
  duration: 600,
  savedAt: new Date(),
  isCompleted: false,
  inferredSkills: ['javascript'],
  inferredCareers: ['frontend-developer'],
  codelearnnScore: 85,
  ...overrides
});

/**
 * Create a test AI suggestion
 */
const createTestAISuggestion = (pathId, userId, overrides = {}) => ({
  _id: new mongoose.Types.ObjectId(),
  pathId,
  userId,
  suggestionType: 'add_video',
  trigger: 'video_added',
  proposedChanges: {
    action: 'add_node',
    videoId: 'suggested-video-1',
    title: 'Suggested Video',
    reason: 'Complements your current learning'
  },
  reasoning: {
    summary: 'This video is recommended based on your progress',
    details: ['Covers related topics', 'Good continuation'],
    dataPoints: [{ type: 'skill_match', value: 0.8 }]
  },
  confidence: 0.85,
  priority: 'medium',
  status: 'pending',
  createdAt: new Date(),
  expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  ...overrides
});

module.exports = {
  createMockUser,
  generateTestToken,
  mockRequest,
  mockResponse,
  mockNext,
  createTestLearningPath,
  createTestSavedVideo,
  createTestAISuggestion
};
