const mongoose = require('mongoose');

/**
 * CareerRoadmap Schema - Stores complete career roadmaps permanently
 * Generated by AI with real-time web context
 */
const careerRoadmapSchema = new mongoose.Schema({
  // Keyword used to generate roadmap
  keyword: {
    type: String,
    required: true,
    trim: true,
    lowercase: true,
    unique: true,
    index: true
  },

  // Content moderation status
  isAppropriate: {
    type: Boolean,
    required: true,
    default: true
  },
  moderationReason: String,

  // Technology/Field Overview
  overview: {
    name: String,
    description: String,
    latestVersion: String,
    releaseDate: String,
    officialWebsite: String,
    category: String,
    subcategory: String
  },

  // Current Market Conditions
  marketInsights: {
    demandLevel: {
      type: String,
      enum: ['Very Low', 'Low', 'Medium', 'High', 'Very High', 'Extreme']
    },
    growthRate: String,
    averageSalary: {
      entry: { min: Number, max: Number },
      mid: { min: Number, max: Number },
      senior: { min: Number, max: Number },
      currency: { type: String, default: 'USD' }
    },
    topHiringCompanies: [String],
    hotLocations: [String],
    jobCount: Number
  },

  // Related Domains & Fields (expanded search)
  relatedDomains: [{
    name: String,
    description: String,
    relevanceScore: Number,
    jobTitles: [String],
    skills: [String]
  }],

  // Step-by-Step Learning Roadmap
  roadmap: {
    prerequisites: [{
      skill: String,
      importance: String,
      resources: [String]
    }],
    phases: [{
      phase: Number,
      title: String,
      duration: String,
      objectives: [String],
      skills: [String],
      projects: [String],
      resources: [{
        name: String,
        type: String,
        url: String,
        isFree: Boolean
      }]
    }],
    certifications: [{
      name: String,
      provider: String,
      cost: String,
      difficulty: String,
      url: String
    }],
    timeline: {
      beginnerToJob: String,
      beginnerToMid: String,
      beginnerToSenior: String
    }
  },

  // Career Progression
  careerPath: {
    entryLevel: [{
      title: String,
      salaryRange: String,
      companies: [String]
    }],
    midLevel: [{
      title: String,
      salaryRange: String,
      yearsExperience: String
    }],
    seniorLevel: [{
      title: String,
      salaryRange: String,
      yearsExperience: String
    }],
    leadership: [{
      title: String,
      salaryRange: String
    }]
  },

  // Real-time job listings snapshot
  latestJobs: [{
    title: String,
    company: String,
    location: String,
    salary: String,
    postedAt: Date,
    applyUrl: String
  }],

  // AI generation metadata
  generatedBy: {
    model: String,
    webContextUsed: Boolean,
    webSearchDate: Date
  },

  // Usage tracking
  usageCount: {
    type: Number,
    default: 1
  },
  lastAccessedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

// Indexes
careerRoadmapSchema.index({ 'overview.category': 1 });
careerRoadmapSchema.index({ usageCount: -1 });
careerRoadmapSchema.index({ 'marketInsights.demandLevel': 1 });

/**
 * Static: Find by keyword
 */
careerRoadmapSchema.statics.findByKeyword = async function(keyword) {
  const normalized = keyword.toLowerCase().trim();
  
  const cached = await this.findOneAndUpdate(
    { keyword: normalized },
    { 
      $inc: { usageCount: 1 },
      $set: { lastAccessedAt: new Date() }
    },
    { new: true }
  );
  return cached;
};

/**
 * Static: Save roadmap
 */
careerRoadmapSchema.statics.saveRoadmap = async function(keyword, data) {
  const normalized = keyword.toLowerCase().trim();
  
  try {
    return await this.findOneAndUpdate(
      { keyword: normalized },
      { $set: { keyword: normalized, ...data, lastAccessedAt: new Date() } },
      { upsert: true, new: true }
    );
  } catch (error) {
    if (error.code !== 11000) throw error;
    return this.findOne({ keyword: normalized });
  }
};

/**
 * Static: Get popular roadmaps
 */
careerRoadmapSchema.statics.getPopular = async function(limit = 10) {
  return this.find({ isAppropriate: true })
    .sort({ usageCount: -1 })
    .limit(limit)
    .select('keyword overview.name overview.category marketInsights.demandLevel usageCount');
};

const CareerRoadmap = mongoose.model('CareerRoadmap', careerRoadmapSchema);

module.exports = CareerRoadmap;
